### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayesha765**

### CODE REVIEW

**Review by AquibPy — CHANGES_REQUESTED** [review]
You don't have to update the read me.
The task is just mention your name and class in members.md

**Comment by Ayesha765** [comment]
Thank You. The task has been corrected.

**Comment by Ayesha765** [comment]
Thank You. The task has been corrected.

**Comment by Ayesha765** [comment]
Thank You. The task has been corrected.

**Comment by farazkhanfk7** [comment]
@Ayesha765  NIcely done. LGTM :+1:

**Pull request merged**
