### PR TITLE
Image filters

### PR DESCRIPTION
**Pull request by sonal-spd**

### CODE REVIEW

**Comment by farazkhanfk7** [comment]
@sonal-spd Nice work :+1:   But there are some merge conflicts that need to be resolved. The reason behind this is some other members have also added their name after you cloned the repo and those changes are conflicting with your branch. This happens many times in open-source contribution.
Please pull the recent changes from this upstream repository and make commits to the same branch. Let me know if any help is needed.

**Comment by sonal-spd** [comment]
Do I have to do clone it again and do all things again??

**Comment by farazkhanfk7** [comment]
There are actually two ways of solving merge conflicts.
1. Easy One : 
    * Delete your previous fork and create a new one.
    *  Follow the same steps and submit a new PR.
 2. The Command-line method : 
    * Add upstream branch : `$ git remote add upstream https://github.com/ADC-Club-AMU/Learning-Git.git`
    * Fetch it on your local machine : `$ git fetch upstream`
    * Check available remotes and branches with `$ git remote -v` and `$ git branch -a`
    *  Switch to your original branch : `$ git checkout ImageFilters` and make sure you're on this branch before proceeding further.
    * Pull the upstream(ADC) branch to your ImageFilters branch : `$ git pull upstream main`
    *  Now make suitable changes with your code-editor and make sure other member's work is now present in your local repo. Make sure your changes are in accordance with the desired format.
    * Now add your changes : `git add .` and `git commit -m "resolved conflicts"`
    * Push your changes to your ImageFilters branch : `$ git push origin ImageFilters` 

You can use any of these two. There is also a rebasing method but I won't recommend that ( a little tricky). This could work.

**Comment by farazkhanfk7** [comment]
@sonal-spd Looks good. Though there is still some unwanted text like HEAD and commit hash due to 'merging' of both branches, but it can be merged. Nice work :+1:

**Pull request merged**
